theme: jekyll-theme-cayman
title: Some useful yet simple tools for everyday work in AutoCad 
description: These files can be loaded and run on any version of Autocad. Some of the tools are made to match Serbian cadastre standars, others are with wider range of use.  
